#!/bin/sh

red=$'\e[1;31m'
mag=$'\e[1;35m'
end=$'\e[0m'
bld=$'\e[1m'
dim=$'\e[2m'

hydrate() {
  for pkg in `ls src`; do
    (cd src && stow --target=$HOME $pkg)
    printf "${dim}[link]${end} $pkg\n"
  done
}

printf "install dotfiles? ${bld}[y/n]${end} ${red}>>${end} "

while true; do
  read yn
  case $yn in
    [Yy]*) break ;;
    [Nn]*) exit ;;
    *) printf "${bld}[y/n]${end} ${red}>>${end} " ;;
  esac
done

hydrate

printf "${mag}[done]${end} 🏄sankyu ja🏽"
