cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/homebrew-php'
tap 'caskroom/versions'

brew 'bash'
brew 'coreutils', args: ['with-default-names']
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'grep', args: ['with-default-names']
brew 'less'
brew 'moreutils', args: ['with-default-names']
brew 'nano'
brew 'node'
brew 'openssh'
brew 'php-code-sniffer'
brew 'python'
brew 'rbenv'
brew 'rsync'
brew 'stow'
brew 'swiftlint'
brew 'the_silver_searcher'
brew 'vim' , args: ['--override-system-vi']
brew 'wget'
brew 'yarn'
brew 'z'

cask 'atom'
cask 'google-chrome'
